### ISSUE TITLE
the existing captioning file about mscoco2014test?

### ISSUE THREAD

**Issue by hwbhwbgao** [cvpr-anon/captioning#11]
Excuse me,where can I download the existing captioning file about mscoco 2014test? Can you upload it easily. Thank you！

**Comment by zxh19976666** [comment]
Hello！how to get the aoa_caps/results_train_beam+str(beam).json?
thanks!

**Comment by zxh19976666** [comment]
excuse me sir，do you solve this problem？I don't know how to get the existing captioning file.
