### ISSUE TITLE
I'm struggling on running tsv.py

### ISSUE THREAD

**Issue by KwonDaYeong** [cvpr-anon/captioning#12]
As the instruction I downloaded the file 'trainval_36', unzipped it and place it at 'bottom-up_features'.
I ran code "python bottom-up_features/tsv.py" and it raises error that no such file or directory: '../data/train2014'. Is there any other implementation that I should do before run the code "../data/train2014" except placing 'trainval_36' file at "bottom-up_features" folder?

*I'm using google colab

**Comment by zxh19976666** [comment]
Hello！how to get the aoa_caps/results_train_beam+str(beam).json?
thanks!
