### ISSUE TITLE
about download caption data

### ISSUE THREAD

**Issue by zxh19976666** [cvpr-anon/captioning#13]
how to download the existing captios to be edited？or how to download AoAnet captions result ？thanks！

**Comment by fawazsammani** [comment]
Please see "Download/Prepare Caption Data" section

**Comment by zxh19976666** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by zxh19976666** [comment]
> Please see "Download/Prepare Caption Data" section

Sorry Sir，

for split,beam in zip(splits,beams):
    with open('aoa_caps/results_' + split + '_beam ` + str(beam).json', 'r') as j:
        captions = json.load(j)

How to get the aoa_caps/results_？
