### ISSUE TITLE
How to output textual alignment plots？

### ISSUE THREAD

**Issue by zxh19976666** [cvpr-anon/captioning#14]
I see the textual alignment plots in your paper，but how to output it？thank you

**Comment by fawazsammani** [comment]
Hi, This is the code I used:

```
def showAttention(input_sentence, seq, attentions, rev_word_map):
    
    words = [rev_word_map[ind] for ind in seq if ind!=word_map['<end>']]
    words = words[1:]

    fig = plt.figure()
    ax = fig.add_subplot(111)
    cax = ax.matshow(attentions.numpy(), cmap='bone')
    fig.colorbar(cax)

    # Set up axes
    ax.set_xticklabels([''] + input_sentence.split(' '), rotation=90)
    ax.set_yticklabels([''] + words)

    # Show label at every tick
    ax.xaxis.set_major_locator(ticker.MultipleLocator(1))
    ax.yaxis.set_major_locator(ticker.MultipleLocator(1))
    plt.show()
```
After obtaining `prev_cap` (previous caption from another model) and `seq` (output caption from the modification model like EditNet or DCNet or both combined), as well as `alphastext` (the text attention maps), then you can use:

```
rev_word_map = {v: k for k, v in word_map.items()}
showAttention(prev_cap, seq, alphastext, rev_word_map)
```

The code above is mostly based on [this](https://pytorch.org/tutorials/intermediate/seq2seq_translation_tutorial.html)

**Comment by zxh19976666** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by zxh19976666** [comment]
ok thank you sir，and when i run your code，it show me don‘t have AoAnet captions result ，so  I want to ask if I need to run this code（https://github.com/husthuaan/AoANet） to get the result？This has been bothering me for a long time, I hope you can reply me

**Comment by fawazsammani** [comment]
We already provide the captions from AoANet, you dont have to run it again. Please see [here](https://github.com/fawazsammani/show-edit-tell#downloadprepare-caption-data)

**Comment by zxh19976666** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
