### ISSUE TITLE
is your coco-cap api guranteed?

### ISSUE THREAD

**Issue by Doragd** [cvpr-anon/captioning#2]
hello sir,  thanks for your talent work on show, edit and tell. it really helps me a lot.
I'm choosing one coco eval tool for my project and you choose the https://github.com/mtanti/coco-caption as your eval tools. But i see your issue on https://github.com/salaniz/pycocoevalcap. 
i wanna know why you not choose salaniz/pycocoevalcap ?
is there any wrong with salaniz/pycocoevalcap?
Thanks a lot.

**Comment by fawazsammani** [comment]
Yes, I verified it more than one time. It's 100% identical to the original one written in python 2. You can verify yourself by running the results json file in `outputs/` using the python 2 original coco-caption.

**Comment by Doragd** [comment]
@fawazsammani thanks for your quick reply. 
do you mean the mtanti/coco-caption is 100% identical to the original one written in python 2?
or salaniz/pycocoevalcap?

**Comment by fawazsammani** [comment]
They are all the same. By the way, I appeared to be using the coco-caption [here](https://github.com/ruotianluo/coco-caption) in the code. I think I posted the wrong link in the readme file. I'll update it. Nevetheless, I checked all 3 of them, they are all identical to the original coco-caption.

**Comment by Doragd** [comment]
thanks a lot. acutally so many reseachers are using the ruotianluo/coco-cation.  okey,  i will follow you to use the ruotianluo/coco-caption.

**Comment by zxh19976666** [comment]
Hello！how to get the aoa_caps/results_train_beam+str(beam).json?
thanks!
