### ISSUE TITLE
Some problems about Meshed Transformer

### ISSUE THREAD

**Issue by HN123-123** [cvpr-anon/captioning#5]
Sorry to bother you. I want to test the performence of meshed decoder part in harvardnlp code for transformer followed as the snippet you mentioned in https://github.com/aimagelab/meshed-memory-transformer/issues/4, 
![image](https://user-images.githubusercontent.com/54923253/96393338-6426ff80-11f1-11eb-89f9-43b3a56ed1c9.png)

 but i got the memory'shape [batch_size, num_boxes, d_model] which not contain the num_layers.  For your Transformer model, are there other important things to make it work?
Thanks a lot for your help!

**Comment by fawazsammani** [comment]
You should probably ask this question under the m2 repository. This place is meant for issues under the show-edit-tell work.

**Comment by zxh19976666** [comment]
Hello！how to get the aoa_caps/results_train_beam+str(beam).json?
thanks!
