### ISSUE TITLE
Supplementary material about DCNet.

### ISSUE THREAD

**Issue by whzikaros** [cvpr-anon/captioning#6]
Where is the Supplementary material about DCNet?

**Comment by fawazsammani** [comment]
Hi. The supplementary file isn't in the arXiv version. You have to go the the CVPR publication archive to find it. You can find it [here](https://openaccess.thecvf.com/content_CVPR_2020/supplemental/Sammani_Show_Edit_and_CVPR_2020_supplemental.pdf)

**Comment by whzikaros** [comment]
Thank you!

**Comment by zxh19976666** [comment]
> 

Hello！how to get the aoa_caps/results_train_beam+str(beam).json?
thanks!
