### ISSUE TITLE
Does anyone have a code to visualize the picture and the generated caption???

### ISSUE THREAD

**Issue by qin79** [cvpr-anon/captioning#8]
Enter the picture and print out its caption！thanks！

**Comment by fawazsammani** [comment]
If you want to visualize an image-caption for COCO, simply download the results file which includes the image id of COCO with its generated caption, as well as the COCO dataset. Then show and image and caption you want

**Comment by zxh19976666** [comment]
Hello！how to get the aoa_caps/results_train_beam+str(beam).json?
thanks!

**Comment by zxh19976666** [comment]
> Enter the picture and print out its caption！thanks！

Hello！how to get the aoa_caps/results_train_beam+str(beam).json?
thanks!
