### ISSUE TITLE
aoa_caps

### ISSUE THREAD

**Issue by WUHE-art** [cvpr-anon/captioning#9]
Excuse me, where can I download the existing caption to be edited? And how organize them in a list containing dictionaries with each dictionary. Thank you!

**Comment by fawazsammani** [comment]
Hi, What is the error you are getting in that script?

**Comment by zxh19976666** [comment]
Hello！how to get the aoa_caps/results_train_beam+str(beam).json?
thanks!

**Comment by zxh19976666** [comment]
> Hi, What is the error you are getting in that script?

Hello！how to get the aoa_caps/results_train_beam+str(beam).json?
thanks!
